class EX1{
    public static void main(String[] args) {
       /* int num = 7;
        int num2= 6;

        int result = num1 % num2;

      //num1 = num1+1;
      
      num1++; //increment operator
      num2--; //decrement operator      
        num1+=2; //num1 = num1+2
        ++num1; //pre increment operator
        --num2; //pre decrement operator */
        

        //oprators
        int num1 = 7;
        int num2 = 5;
        
        < less than operator
        > greater than operator 
        == equal to operator
        != not equal to operator
        <= less than or equal to operator
        >= greater than or equal to operator

        eg.
        7<5 false
        7>5 true
    }

}